### ISSUE TITLE
Redesign addon directory using Dashboard v3 (D3) style guide

### ISSUE THREAD

**Issue by linc** [vanilla/community#119]
Site:

* [ ] Rework top-level site nativation. "Docs" and "Cloud" options go to other sites and should not be parallel to "Community" and "Addons". "Blog" can be removed now.
* [ ] Add navigation to Addon directory to mobile theme.

Directory Functionality:

* [ ] Remove "Everything" option. Force selection to Addons, Themes, or Locales.
* [ ] Remove "Core" option. Show Vanilla & Porter in their own areas outside the directory lists.
* [ ] Add "Alphabetical" sort order.

Directory Styling:

* [ ] Rework sidebar info to right-side. Rewrite explainer texts & emphasize open source differences.
* [ ] Implement "Addons" page D3 style for addon directory list.
* [ ] Apply D3 style to addon upload, edit, search, and pagination features.
* [ ] Review and test functionality on mobile.

Single View:

* [ ] Redesign the single addon/theme/locale view using Dashboard v3 style guide.
* [ ] Implement redesigned single view.
